# Generated by Django 4.1.2 on 2022-10-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoverCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Crops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=50)),
                ("cover_crops", models.ManyToManyField(to="crops.covercrop")),
            ],
        ),
    ]
