# Generated by Django 4.1.2 on 2022-10-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="covercrop",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="covercrop",
            name="link",
            field=models.URLField(default="https://www.burpee.com/", max_length=1000),
            preserve_default=False,
        ),
    ]
